// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd-kGIg8IN8j7ikPxWb9OJVt0xR_qNV3g',
    appId: '1:1049122086555:web:90bd8f990f27b0f923303e',
    messagingSenderId: '1049122086555',
    projectId: 'sealine-app',
    authDomain: 'sealine-app.firebaseapp.com',
    storageBucket: 'sealine-app.appspot.com',
    measurementId: 'G-C9518161G0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5JWBPMxSTDmk5rI3zvZFbvQ45O371D7k',
    appId: '1:1049122086555:android:e232c49d3598826d23303e',
    messagingSenderId: '1049122086555',
    projectId: 'sealine-app',
    storageBucket: 'sealine-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmnlvdE2icP_O7A-dlh9i7LaZeb5EL3Zc',
    appId: '1:1049122086555:ios:f05e97a8a48e4e7423303e',
    messagingSenderId: '1049122086555',
    projectId: 'sealine-app',
    storageBucket: 'sealine-app.appspot.com',
    iosClientId: '1049122086555-58vr2mcvlcn9te0ovd083t99r498ptpq.apps.googleusercontent.com',
    iosBundleId: 'com.example.sealineApp',
  );
}
